<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ItemsSeeder extends Seeder
{
    public function run()
    {
        $items = [
            //Bebidas Frias
            [
                'company_id' => 2,
                'name' => 'Heineken 0,0% long neck 330ml',
                'description' => 'Cerveja Heineken 0,0% álcool long neck 330ml',
                'image_url' => 'https://phygital-files.mercafacil.com/catalogo/uploads/produto/cerveja_heineken_sem_lcool_long_neck_330ml_f495cd21-ba3b-47db-9809-ae30cfb875f5.jpg',
                'price' => 7.50,
                'category_id' => 21,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Cerveja Skol 350ml',
                'description' => 'Cerveja Skol 350ml',
                'image_url' => 'https://destro.fbitsstatic.net/img/p/cerveja-skol-lata-350ml-77725/264279.jpg?w=500&h=500&v=no-change&qs=ignore',
                'price' => 3.50,
                'category_id' => 21,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Água Mineral Cristal 500ml',
                'description' => 'Água Mineral 500ml',
                'image_url' => 'https://drogariamoderna.vtexassets.com/arquivos/ids/251997-800-auto?v=638151218022670000&width=800&height=auto&aspect=true',
                'price' => 2.50,
                'category_id' => 1,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Guaraná Antártica lata 350ml',
                'description' => 'Refri Guaraná Antártica lata 350ml',
                'image_url' => 'https://www.imigrantesbebidas.com.br/bebida/images/products/full/1935-refrigerante-guarana-antarctica-lata-350ml.jpg',
                'price' => 3.50,
                'category_id' => 1,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Coca-Cola lata 350ml',
                'description' => 'Refri Coca-Cola lata 350ml',
                'image_url' => 'https://tdc0wy.vteximg.com.br/arquivos/ids/163808-300-300/REFRIGERANTE-COCA-COLA-LATA-350ML-ORIGINAL.png?v=638504173989400000',
                'price' => 4.50,
                'category_id' => 1,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Fanta Laranja lata 350ml',
                'description' => 'Refri Fanta lata 350ml',
                'image_url' => 'https://images.tcdn.com.br/img/img_prod/1115696/fanta_laranja_lata_350ml_6_und_1060_1_6a2ac3681c7ae37f162bf0a4e1b9cc33.jpg',
                'price' => 4.00,
                'category_id' => 1,
                'available' => true,
            ],
            //Bebidas Quentes
            [
                'company_id' => 2,
                'name' => 'Café Expresso',
                'description' => 'Café expresso pequeno',
                'image_url' => 'https://cafeteriaexpress.com.br/wp-content/uploads/2021/08/cafe-expresso.jpg',
                'price' => 3.00,
                'category_id' => 2,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Cappuccino',
                'description' => 'Cappuccino pequeno',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/cappuccino.jpg',
                'price' => 5.00,
                'category_id' => 2,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Chocolate Quente',
                'description' => 'Chocolate quente pequeno',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/chocolate-quente.jpg',
                'price' => 6.00,
                'category_id' => 2,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Chá de Camomila',
                'description' => 'Chá de camomila pequeno',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/cha-de-camomila.jpg',
                'price' => 4.00,
                'category_id' => 2,
                'available' => true,
            ],
            //Sanduíches
            [
                'company_id' => 2,
                'name' => 'Hambúrguer de Carne',
                'description' => 'Hambúrguer de carne com queijo e bacon',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/hamburguer-caseiro.jpg',
                'price' => 12.00,
                'category_id' => 3,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Cheeseburger',
                'description' => 'Cheeseburger com queijo cheddar',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/cheeseburger.jpg',
                'price' => 14.00,
                'category_id' => 3,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Sanduíche de Frango',
                'description' => 'Sanduíche natural de frango',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/sanduiche-natural-de-frango.jpg',
                'price' => 8.50,
                'category_id' => 3,
                'available' => true,
            ],
            //Salgados
            [
                'company_id' => 2,
                'name' => 'Coxinha de Frango',
                'description' => 'Coxinha tradicional de frango com catupiry',
                'image_url' => 'https://i.ytimg.com/vi/V9Wg4oxuvI4/maxresdefault.jpg',
                'price' => 6.00,
                'category_id' => 4,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Empada de Palmito',
                'description' => 'Empada de palmito com massa folhada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/empada-de-palmito.jpg',
                'price' => 5.00,
                'category_id' => 4,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Quibe Frito',
                'description' => 'Quibe frito recheado com carne moída',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/quibe-frito.jpg',
                'price' => 4.00,
                'category_id' => 4,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Esfiha de Carne',
                'description' => 'Esfiha de carne com massa folhada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/esfiha-de-carne.jpg',
                'price' => 3.50,
                'category_id' => 4,
                'available' => true,
            ],
            //Sobremesas
            [
                'company_id' => 2,
                'name' => 'Torta de Chocolate',
                'description' => 'Torta de chocolate com recheio cremoso',
                'image_url' => 'https://static.itdg.com.br/images/1200-675/472cc6cf17efaa668fcb6c24a282a31f/shutterstock-1117106795.jpg',
                'price' => 12.00,
                'category_id' => 5,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Bolo de Cenoura',
                'description' => 'Bolo de cenoura com cobertura de chocolate',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-cenoura.jpg',
                'price' => 10.00,
                'category_id' => 5,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Pudim de Leite',
                'description' => 'Pudim de leite condensado com calda de caramelo',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/pudim-de-leite.jpg',
                'price' => 8.00,
                'category_id' => 5,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Brownie de Chocolate',
                'description' => 'Brownie de chocolate com nozes',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/brownie-de-chocolate.jpg',
                'price' => 6.00,
                'category_id' => 5,
                'available' => true,
            ],
            //Açaí e Smoothies
            [
                'company_id' => 2,
                'name' => 'Açaí na Tigela',
                'description' => 'Açaí com banana e granola',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/acai-na-tigela.jpg',
                'price' => 15.00,
                'category_id' => 6,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Smoothie de Morango',
                'description' => 'Smoothie de morango com iogurte',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/smoothie-de-morango.jpg',
                'price' => 10.00,
                'category_id' => 6,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Milkshake de Chocolate',
                'description' => 'Milkshake de chocolate com chantilly',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/milkshake-de-chocolate.jpg',
                'price' => 8.00,
                'category_id' => 6,
                'available' => true,
            ],
            //Saladas
            [
                'company_id' => 2,
                'name' => 'Salada Caesar',
                'description' => 'Salada Caesar com frango grelhado',
                'image_url' => 'https://static.itdg.com.br/images/640-420/338d91b4f7eb4d7b88720cb848a7c1f5/352753-original.jpg',
                'price' => 18.00,
                'category_id' => 7,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Salada de Frutas',
                'description' => 'Salada de frutas com mel e granola',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/salada-de-frutas.jpg',
                'price' => 10.00,
                'category_id' => 7,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Salada Verde',
                'description' => 'Salada verde com molho de mostarda',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/salada-verde.jpg',
                'price' => 8.00,
                'category_id' => 7,
                'available' => true,
            ],
            //Aperitivos e Petiscos
            [
                'company_id' => 2,
                'name' => 'Batata Frita',
                'description' => 'Porção de batata frita com cheddar e bacon',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/batata-frita-com-cheddar-e-bacon.jpg',
                'price' => 12.00,
                'category_id' => 8,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Bolinho de Bacalhau',
                'description' => 'Porção de bolinho de bacalhau com limão',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/bolinho-de-bacalhau.jpg',
                'price' => 10.00,
                'category_id' => 8,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Camarão Empanado',
                'description' => 'Porção de camarão empanado com molho tártaro',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/camarao-empanado.jpg',
                'price' => 15.00,
                'category_id' => 8,
                'available' => true,
            ],
            //Pratos Rápidos
            [
                'company_id' => 2,
                'name' => 'Strogonoff de Frango',
                'description' => 'Strogonoff de frango com arroz e batata palha',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/strogonoff-de-frango.jpg',
                'price' => 20.00,
                'category_id' => 9,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Filé de Frango Grelhado',
                'description' => 'Filé de frango grelhado com legumes',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/file-de-frango-grelhado.jpg',
                'price' => 18.00,
                'category_id' => 9,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Macarrão à Carbonara',
                'description' => 'Macarrão à carbonara com bacon e queijo',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/macarrao-a-carbonara.jpg',
                'price' => 16.00,
                'category_id' => 9,
                'available' => true,
            ],
            //Vegetarianas/Veganas
            [
                'company_id' => 2,
                'name' => 'Hambúrguer Vegetariano',
                'description' => 'Hambúrguer vegetariano com molho especial',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/hamburguer-vegetariano.jpg',
                'price' => 15.00,
                'category_id' => 10,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Sanduíche Vegano',
                'description' => 'Sanduíche vegano com pasta de grão-de-bico',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/sanduiche-vegano.jpg',
                'price' => 12.00,
                'category_id' => 10,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Salada Vegana',
                'description' => 'Salada vegana com molho de mostarda',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/salada-vegana.jpg',
                'price' => 10.00,
                'category_id' => 10,
                'available' => true,
            ],
            //Pizzas e Focaccias
            [
                'company_id' => 2,
                'name' => 'Pizza de Calabresa',
                'description' => 'Pizza de calabresa com queijo e molho de tomate',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/pizza-de-calabresa.jpg',
                'price' => 25.00,
                'category_id' => 11,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Pizza Portuguesa',
                'description' => 'Pizza de Portuguesa com queijo e molho de tomate',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/pizza-de-portuguesa.jpg',
                'price' => 25.00,
                'category_id' => 11,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Pizza de Alho e Óleo',
                'description' => 'Pizza de alho com queijo e molho de tomate',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/pizza-de-alho.jpg',
                'price' => 25.00,
                'category_id' => 11,
                'available' => true,
            ],
            //Doces e Guloseimas
            [
                'company_id' => 2,
                'name' => 'Brigadeiro',
                'description' => 'Brigadeiro tradicional com granulado',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/brigadeiro.jpg',
                'price' => 2.00,
                'category_id' => 12,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Beijinho',
                'description' => 'Beijinho de coco com cravo',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/beijinho.jpg',
                'price' => 2.00,
                'category_id' => 12,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Trufas',
                'description' => 'Trufas de chocolate com recheio cremoso',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/trufas.jpg',
                'price' => 3.00,
                'category_id' => 12,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Gelatina de Morango',
                'description' => 'Gelatina de morango com creme de leite',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/gelatina-de-morango.jpg',
                'price' => 4.00,
                'category_id' => 12,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Pipoca Doce',
                'description' => 'Pipoca doce com caramelo e chocolate',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/pipoca-doce.jpg',
                'price' => 5.00,
                'category_id' => 12,
                'available' => true,
            ],
            //Pães e Torradas
            [
                'company_id' => 2,
                'name' => 'Pão Francês',
                'description' => 'Pão francês com manteiga',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/pao-frances.jpg',
                'price' => 2.00,
                'category_id' => 13,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Torradas',
                'description' => 'Torradas com geleia de morango',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/torradas.jpg',
                'price' => 3.00,
                'category_id' => 13,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Baguete',
                'description' => 'Baguete com presunto e queijo',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/baguete.jpg',
                'price' => 5.00,
                'category_id' => 13,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Pão de Forma',
                'description' => 'Pão de forma com requeijão',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/pao-de-forma.jpg',
                'price' => 4.00,
                'category_id' => 13,
                'available' => true,
            ],
            //Acompanhamentos
            [
                'company_id' => 2,
                'name' => 'Ketchup',
                'description' => 'Ketchup tradicional',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/ketchup.jpg',
                'price' => 1.00,
                'category_id' => 14,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Maionese',
                'description' => 'Maionese temperada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/maionese.jpg',
                'price' => 1.00,
                'category_id' => 14,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Mostarda',
                'description' => 'Mostarda amarela',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/mostarda.jpg',
                'price' => 1.00,
                'category_id' => 14,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Molhos Especiais',
                'description' => 'Molhos especiais para hambúrguer',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/molhos-especiais.jpg',
                'price' => 2.00,
                'category_id' => 14,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Maionese Temperada',
                'description' => 'Maionese temperada com ervas',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/maionese-temperada.jpg',
                'price' => 2.00,
                'category_id' => 14,
                'available' => true,
            ],
            //Sucos Naturais
            [
                'company_id' => 2,
                'name' => 'Suco de Laranja',
                'description' => 'Suco de laranja natural',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/suco-de-laranja.jpg',
                'price' => 5.00,
                'category_id' => 15,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Suco de Limão',
                'description' => 'Suco de limão natural',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/suco-de-limao.jpg',
                'price' => 4.00,
                'category_id' => 15,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Suco de Maracujá',
                'description' => 'Suco de maracujá natural',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/suco-de-maracuja.jpg',
                'price' => 5.00,
                'category_id' => 15,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Suco Detox',
                'description' => 'Suco detox de couve e gengibre',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/suco-detox.jpg',
                'price' => 6.00,
                'category_id' => 15,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Suco de Polpa',
                'description' => 'Suco de polpa de frutas variadas',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/suco-de-polpa.jpg',
                'price' => 7.00,
                'category_id' => 15,
                'available' => true,
            ],
            //Combo de Refeições
            [
                'company_id' => 2,
                'name' => 'Combo de Hambúrguer',
                'description' => 'Combo de hambúrguer + batata frita + refrigerante',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/combo-de-hamburguer.jpg',
                'price' => 25.00,
                'category_id' => 16,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Combo de Sanduíches',
                'description' => 'Combo de sanduíches + batata frita + refrigerante',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/combo-de-sanduiches.jpg',
                'price' => 20.00,
                'category_id' => 16,
                'available' => true,
            ],
            //Refeições em geral
            [
                'company_id' => 2,
                'name' => 'Prato Executivo',
                'description' => 'Prato executivo com arroz, feijão, carne e salada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/prato-executivo.jpg',
                'price' => 18.00,
                'category_id' => 17,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Prato do Dia',
                'description' => 'Prato do dia com arroz, feijão, carne e salada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/prato-do-dia.jpg',
                'price' => 15.00,
                'category_id' => 17,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Prato Especial',
                'description' => 'Prato especial com arroz, feijão, carne e salada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/prato-especial.jpg',
                'price' => 20.00,
                'category_id' => 17,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Prato Alacarte',
                'description' => 'Prato alacarte com arroz, feijão, carne e salada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/prato-alacarte.jpg',
                'price' => 22.00,
                'category_id' => 17,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Quentinhas',
                'description' => 'Quentinhas com arroz, feijão, carne e salada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/quentinhas.jpg',
                'price' => 18.00,
                'category_id' => 17,
                'available' => true,
            ],
            //Especiais do Dia
            [
                'company_id' => 2,
                'name' => 'Prato Especial do Dia',
                'description' => 'Prato especial do dia com arroz, feijão, carne e salada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/prato-especial-do-dia.jpg',
                'price' => 20.00,
                'category_id' => 18,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Prato do Chef',
                'description' => 'Prato do chef com arroz, feijão, carne e salada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/prato-do-chef.jpg',
                'price' => 25.00,
                'category_id' => 18,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Prato Especial da Casa',
                'description' => 'Prato especial da casa com arroz, feijão, carne e salada',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/prato-especial-da-casa.jpg',
                'price' => 22.00,
                'category_id' => 18,
                'available' => true,
            ],
            //Kids
            [
                'company_id' => 2,
                'name' => 'Hambúrguer Kids',
                'description' => 'Hambúrguer kids com batata frita e refrigerante',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/hamburguer-kids.jpg',
                'price' => 12.00,
                'category_id' => 19,
                'available' => true,
            ],
            //Caldos e Sopas
            [
                'company_id' => 2,
                'name' => 'Caldo de Feijão',
                'description' => 'Caldo de feijão com bacon e torradas',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/caldo-de-feijao.jpg',
                'price' => 10.00,
                'category_id' => 20,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Sopa de Legumes',
                'description' => 'Sopa de legumes com macarrão e frango',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/sopa-de-legumes.jpg',
                'price' => 12.00,
                'category_id' => 20,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Canja de Galinha',
                'description' => 'Canja de galinha com arroz e batata',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/canja-de-galinha.jpg',
                'price' => 15.00,
                'category_id' => 20,
                'available' => true,
            ],
            [
                'company_id' => 2,
                'name' => 'Creme de Mandioquinha',
                'description' => 'Creme de mandioquinha com bacon e torradas',
                'image_url' => 'https://www.receiteria.com.br/wp-content/uploads/creme-de-mandioquinha.jpg',
                'price' => 14.00,
                'category_id' => 20,
                'available' => true,
            ],
        ];

        foreach ($items as $item) {
            $timestamp = now()->timestamp; // Pega o timestamp atual
            $slug = Str::slug($item['name']) . '-' . $timestamp; // Gera o slug com timestamp

            Item::create(array_merge($item, [
                'slug' => $slug,
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
